### ISSUE TITLE
Issue with 00_rmChr

### ISSUE THREAD

**Issue by dustin-mullaney** [RitataLU/ATACgraph#11]
I installed ATACgraph according to instructions, and attempted to run the demo. Not sure if it's user error, but the first command, 00_rmChr doesn't work for me:

`$ ATACgraph 00_rmChr -h`
```
/Users/usr/programs/ATACgraph/script/ATACgraph:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/Users/usr/programs/ATACgraph/script/ATACgraph", line 36, in <module>
    module = imp.load_source(tool, filename)
  File "/Users/usr/opt/anaconda3/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/mullaneydb/programs/ATACgraph/script/00_rmChr.py", line 15
    print "Chromosome {} is not in the list. Please check!".format(eachTarget)
          ^
SyntaxError: invalid syntax
```

I get the same error when I try and run the command on the demo materials as in the tutorial: 

`$ ATACgraph 00_rmChr demo.bam demo_rmM.bam chrM`

**Comment by dustin-mullaney** [comment]
I realize now this happens on any of the modules which use imp, and that ATACgraph requires python2.

**Comment by reyesrac** [comment]
Changing the python version to 2.7 ended up giving me more issues in following the demo down the line. Where you able to resolve your issue and run the full demo? Thanks

**Comment by dustin-mullaney** [comment]
> Changing the python version to 2.7 ended up giving me more issues in following the demo down the line. Where you able to resolve your issue and run the full demo? Thanks

I did manage to get it to work and run the full demo, though I had some problems with the dependencies, and resolved them with these installs:
```
conda install -n your_py2.7_env -c bioconda MACS2
conda install -n your_py2.7_env -c bioconda deeptools=3.3.0
conda install -n your_py2.7_env Numpy
conda install -n your_py2.7_env pandas
conda install -n your_py2.7_env pysam==0.11.2.2
conda install -n your_py2.7_env matplotlib
conda install -n your_py2.7_env argparse
conda install -n your_py2.7_env pybedtools
conda install -n your_py2.7_env scikit-learn
```

All of this being said, I have found it somewhat more simple, especially if you need some added flexibility, to just use deeptools independently to visualize ATAC data, at least for my scenario.

**Comment by reyesrac** [comment]
Thank you! I still ran into conflicts when installing the dependencies using your installs.

Will look into using deeptools directly as suggested and other potential workflows/tools. Have you found any good bulk ATAC-seq and RNA-seq integration tools by chance? Thanks again!

__________________
Rachel E Reyes, PhD | Research Associate
Children's Hospital Los Angeles, Department of Pathology
Saban Research Institute
4661 Sunset Blvd.
3rd Floor – MS# 043
Los Angeles, CA  90027
Office: 323-361-6681  |  ***@***.******@***.***>


On May 16, 2023, at 11:06 AM, dustin-mullaney ***@***.***> wrote:

﻿

Changing the python version to 2.7 ended up giving me more issues in following the demo down the line. Where you able to resolve your issue and run the full demo? Thanks

I did manage to get it to work and run the full demo, though I had some problems with the dependencies, and resolved them with these installs:

conda install -n your_py2.7_env -c bioconda MACS2
conda install -n your_py2.7_env -c bioconda deeptools=3.3.0
conda install -n your_py2.7_env Numpy
conda install -n your_py2.7_env pandas
conda install -n your_py2.7_env pysam==0.11.2.2
conda install -n your_py2.7_env matplotlib
conda install -n your_py2.7_env argparse
conda install -n your_py2.7_env pybedtools
conda install -n your_py2.7_env scikit-learn


All of this being said, I have found it somewhat more simple, especially if you need some added flexibility, to just use deeptools independently to visualize ATAC data, at least for my scenario.

**Comment by reyesrac** [comment]
Greetings!

I ran into this error with GUAVA while it tried to open a GUI. Can I not do that within the commandline?:
https://github.com/MayurDivate/GUAVA/tree/master
[https://opengraph.githubassets.com/6bd70af275df49b09ddea985bd46854cbb130e91ea09af1dd198a0e155765ea7/MayurDivate/GUAVA]<https://github.com/MayurDivate/GUAVA/tree/master>
GitHub - MayurDivate/GUAVA: GUAVA : A GUI tool for the Analysis and Visualization of ATAC-seq data<https://github.com/MayurDivate/GUAVA/tree/master>
GUAVA : A GUI tool for the Analysis and Visualization of ATAC-seq data - GitHub - MayurDivate/GUAVA: GUAVA : A GUI tool for the Analysis and Visualization of ATAC-seq data
github.com



(env-guava) ***@***.*** GUAVA-1.0.1]$ java -jar GUAVA.jar

GUAVA version 1

Exception in thread "main" java.awt.HeadlessException:

No X11 DISPLAY variable was set, but this program performed an operation which requires it.



Thank you! I gave up on the ATACgraph tool and now am trying NextFlow-workflow tools and GUAVA.

-Rachel
________________________________
